title: My computer sciense blog
email: ariel415el@gmai.com
description: >- # this means to ignore newlines until "baseurl:"
  Notes in my learning
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  ariel415el

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
